#! /usr/bin/perl

chomp ($prog = `basename $0`);
$RANGE = 10;
$PERIOD = 1.0;
$FLOOR = 0;

sub usage () {
$out = <<DUH

    $prog [RANGE [PERIOD [FLOOR]]

    Output to STDOUT a random *integer* with lower bound of FLOOR and a
    RANGE-1 every PERIOD seconds.  RANGE defaults to $RANGE, PERIOD to
    $PERIOD, and FLOOR to $FLOOR.

DUH
;
print STDERR $out;
exit;
}

if ( $ARGV[0] =~ /\-h/ ) {
    usage();
}

if ( $ARGV[0] =~ /(\d)+/ ) {
    $RANGE = $ARGV[0];
}
if ( $ARGV[1] =~ /(\d)+/ ) {
    $PERIOD = $ARGV[1];
}
if ( $ARGV[2] =~ /(\d)+/ ) {
    $FLOOR = $ARGV[2];
}

$| = 1;
while (1) {
    $rand = int(rand($RANGE)) + $FLOOR;
    print "$rand\n";
# This is a sleep
    select(undef, undef, undef, $PERIOD);
}


